[package]
name = "compass-query"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
regex.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
compass-cypher = { path = "../compass-cypher", version = "0.2.1" }
compass-model = { path = "../compass-model", version = "0.2.1" }
compass-analysis = { path = "../compass-analysis", version = "0.2.1" }
compass-ir = { path = "../compass-ir", version = "0.2.1" }
compass-store = { path = "../compass-store", version = "0.2.1" }
unicode-normalization.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"
rustix.workspace = true

[dev-dependencies]
compass-graph = { path = "../compass-graph", version = "0.2.1" }
compass-graphdb = { path = "../compass-graphdb", version = "0.2.1" }
compass-languages = { path = "../compass-languages", version = "0.2.1" }
tempfile.workspace = true

[lints]
workspace = true
