[package]
name = "compass-resolve"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
ahash.workspace = true
rayon.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
thiserror.workspace = true
compass-files = { path = "../compass-files", version = "0.3.1" }
compass-languages = { path = "../compass-languages", version = "0.3.1" }
compass-model = { path = "../compass-model", version = "0.3.1" }
compass-program = { path = "../compass-program", version = "0.3.1" }

[lints]
workspace = true

[dev-dependencies]
compass-ir = { path = "../compass-ir", version = "0.3.1" }
compass-graph = { path = "../compass-graph", version = "0.3.1" }
tempfile.workspace = true
