use std::path::PathBuf;

use compass_transcribe::audio::{AudioLimits, WHISPER_SAMPLE_RATE, decode_audio};

#[test]
#[ignore = "decodes a real AVI generated by an independent media implementation"]
fn decodes_real_avi_fixture() -> Result<(), Box<dyn std::error::Error>> {
    let path = PathBuf::from(std::env::var("COMPASS_AVI_ACCEPTANCE_FILE")?);
    let decoded = decode_audio(&path, AudioLimits::default())?;
    assert_eq!(decoded.sample_rate, WHISPER_SAMPLE_RATE);
    assert!(!decoded.samples.is_empty());
    assert!(decoded.samples.iter().all(|sample| sample.is_finite()));
    Ok(())
}
