[package]
name = "compass-ocr"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
image.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tempfile.workspace = true
thiserror.workspace = true
ureq.workspace = true

[target.'cfg(not(all(target_os = "macos", target_arch = "x86_64")))'.dependencies]
oar-ocr.workspace = true

[lints]
workspace = true
