[package]
name = "compass-output"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
ahash.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true
thiserror.workspace = true
time.workspace = true
compass-files = { path = "../compass-files", version = "0.3.10" }
compass-analysis = { path = "../compass-analysis", version = "0.3.10" }
compass-cypher = { path = "../compass-cypher", version = "0.3.10" }
compass-graph = { path = "../compass-graph", version = "0.3.10" }
compass-history = { path = "../compass-history", version = "0.3.10" }
compass-model = { path = "../compass-model", version = "0.3.10" }
compass-pr-intelligence = { path = "../compass-pr-intelligence", version = "0.3.10" }
compass-query = { path = "../compass-query", version = "0.3.10" }
unicode-normalization.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
