use std::path::Path;

use trail_files::write_text_atomic;
use trail_model::GraphDocument;

use crate::OutputError;

#[must_use]
pub fn cypher_document(document: &GraphDocument) -> String {
    let mut lines = vec![
        "// Neo4j Cypher import - generated by /graphify".to_owned(),
        String::new(),
    ];
    for node in &document.nodes {
        let label = cypher_escape(node.label());
        let id = cypher_escape(&node.id);
        let raw_type = node
            .attributes
            .get("file_type")
            .and_then(serde_json::Value::as_str)
            .unwrap_or("unknown");
        let mut capitalized = raw_type.to_lowercase();
        if let Some(first) = capitalized.get_mut(0..1) {
            first.make_ascii_uppercase();
        }
        let node_type = cypher_identifier(&capitalized, "Entity");
        lines.push(format!(
            "MERGE (n:{node_type} {{id: '{id}', label: '{label}'}});"
        ));
    }
    lines.push(String::new());
    for edge in &document.links {
        let relation = edge
            .attributes
            .get("relation")
            .and_then(serde_json::Value::as_str)
            .unwrap_or("RELATES_TO")
            .to_uppercase();
        let relation = cypher_identifier(&relation, "RELATES_TO");
        let confidence = cypher_escape(
            edge.attributes
                .get("confidence")
                .and_then(serde_json::Value::as_str)
                .unwrap_or("EXTRACTED"),
        );
        let source = cypher_escape(&edge.source);
        let target = cypher_escape(&edge.target);
        lines.push(format!(
            "MATCH (a {{id: '{source}'}}), (b {{id: '{target}'}}) MERGE (a)-[:{relation} {{confidence: '{confidence}'}}]->(b);"
        ));
    }
    lines.join("\n")
}

pub fn write_cypher(
    document: &GraphDocument,
    output_path: impl AsRef<Path>,
) -> Result<(), OutputError> {
    write_text_atomic(output_path, &cypher_document(document))?;
    Ok(())
}

fn cypher_escape(value: &str) -> String {
    value
        .chars()
        .filter(|character| *character >= ' ' || *character == '\t')
        .collect::<String>()
        .replace('\\', "\\\\")
        .replace('\'', "\\'")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
}

fn cypher_identifier(value: &str, fallback: &str) -> String {
    let cleaned = value
        .chars()
        .filter(|character| character.is_ascii_alphanumeric() || *character == '_')
        .collect::<String>();
    if cleaned
        .chars()
        .next()
        .is_some_and(|character| character.is_ascii_alphabetic())
    {
        cleaned
    } else {
        fallback.to_owned()
    }
}
