[package]
name = "compass-store-redb"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
compass-store = { path = "../compass-store", version = "0.3.11" }
redb.workspace = true
sha2.workspace = true

[dev-dependencies]
compass-graph = { path = "../compass-graph", version = "0.3.11" }
compass-model = { path = "../compass-model", version = "0.3.11" }
compass-store = { path = "../compass-store", version = "0.3.11", features = ["test-support"] }
tempfile.workspace = true

[lints]
workspace = true
