complete -c compass -f -n '__fish_use_subcommand' -a 'init update extract watch serve cluster-only query path explain affected tree export benchmark diagnose merge-graphs history'
complete -c compass -n '__fish_seen_subcommand_from init' -l include -r -d 'Include a file, folder, or glob'
complete -c compass -n '__fish_seen_subcommand_from init' -l exclude -r -d 'Exclude a project-relative glob'
complete -c compass -n '__fish_seen_subcommand_from init' -l yes -d 'Accept without prompting'
complete -c compass -n '__fish_seen_subcommand_from init' -l force -d 'Replace existing configuration'
complete -c compass -f -n '__fish_seen_subcommand_from history; and not __fish_seen_subcommand_from enable disable status build rebuild list show prefer export gc' -a 'enable disable status build rebuild list show prefer export gc'
complete -c compass -n '__fish_seen_subcommand_from history; and __fish_seen_subcommand_from build' -l all -d 'Build every commit reachable from REF'
complete -c compass -n '__fish_seen_subcommand_from history; and __fish_seen_subcommand_from build' -l first-parent -d 'Build only the first-parent lineage'
complete -c compass -f -n '__fish_seen_subcommand_from export' -a 'html callflow-html obsidian wiki svg graphml'
complete -c compass -f -n '__fish_seen_subcommand_from diagnose' -a multigraph
complete -c compass -l help -d 'Show help'
complete -c compass -l version -d 'Show version'
complete -c compass -l graph -r -d 'Path to graph.json'
complete -c compass -l out -r -d 'Output directory'
complete -c compass -l no-cluster -d 'Skip clustering'
complete -c compass -l no-viz -d 'Skip visualization'
complete -c compass -n '__fish_seen_subcommand_from serve' -l transport -r -a 'stdio http' -d 'MCP transport'
complete -c compass -n '__fish_seen_subcommand_from serve' -l host -r -d 'HTTP bind host'
complete -c compass -n '__fish_seen_subcommand_from serve' -l port -r -d 'HTTP bind port'
complete -c compass -n '__fish_seen_subcommand_from serve' -l api-key -r -d 'HTTP API key'
complete -c compass -n '__fish_seen_subcommand_from serve' -l path -r -d 'HTTP mount path'
complete -c compass -n '__fish_seen_subcommand_from serve' -l json-response -d 'Return JSON instead of SSE'
complete -c compass -n '__fish_seen_subcommand_from serve' -l stateless -d 'Disable session state'
complete -c compass -n '__fish_seen_subcommand_from serve' -l session-timeout -r -d 'Session expiry in seconds'
