use std::fs;
use std::io::Read;
use std::path::{Component, Path, PathBuf};

use glob::Pattern;

const GENERATED_HEADER_BYTES: usize = 2_048;
const ATTRIBUTES_FILE_BYTES: u64 = 256 * 1024;
const MAX_ATTRIBUTE_DEPTH: usize = 64;

/// Determine whether a source is explicitly or conventionally generated.
///
/// The decision is bounded and deterministic. It admits source headers,
/// conventional generated paths/filenames, and the `linguist-generated`
/// attribute from project-contained `.gitattributes` files. It does not infer
/// generation from line length, entropy, or formatting style.
#[must_use]
pub fn source_is_generated(root: &Path, path: &Path) -> bool {
    generated_header(path)
        || generated_path(root, path)
        || generated_attribute(root, path).unwrap_or(false)
}

fn generated_header(path: &Path) -> bool {
    fs::File::open(path).ok().is_some_and(|file| {
        let mut bytes = Vec::with_capacity(GENERATED_HEADER_BYTES);
        if file
            .take(GENERATED_HEADER_BYTES as u64)
            .read_to_end(&mut bytes)
            .is_err()
        {
            return false;
        }
        let head = String::from_utf8_lossy(&bytes);
        ["DO NOT EDIT", "@generated", "Generated by"]
            .iter()
            .any(|marker| head.contains(marker))
    })
}

fn generated_path(root: &Path, path: &Path) -> bool {
    let relative = path.strip_prefix(root).unwrap_or(path);
    let components = relative
        .components()
        .filter_map(|component| match component {
            Component::Normal(value) => Some(value.to_string_lossy().to_ascii_lowercase()),
            _ => None,
        })
        .collect::<Vec<_>>();
    let filename = components.last().map_or("", String::as_str);
    let root_output = components.first().is_some_and(|component| {
        matches!(
            component.as_str(),
            "generated" | "gen" | "dist" | "build" | "target" | ".next"
        )
    });
    let explicit_generated = components
        .iter()
        .any(|component| matches!(component.as_str(), "generated" | "gen"));
    root_output
        || explicit_generated
        || filename.contains(".generated.")
        || filename.contains("_generated.")
        || filename.ends_with(".min.js")
        || filename.ends_with(".min.css")
}

fn generated_attribute(root: &Path, path: &Path) -> Option<bool> {
    let relative = path.strip_prefix(root).ok()?;
    let mut directories = Vec::<PathBuf>::new();
    let mut current = path.parent()?;
    while current.starts_with(root) && directories.len() < MAX_ATTRIBUTE_DEPTH {
        directories.push(current.to_path_buf());
        if current == root {
            break;
        }
        current = current.parent()?;
    }
    directories.reverse();
    let mut decision = None;
    for directory in directories {
        let attributes_path = directory.join(".gitattributes");
        let Ok(metadata) = fs::metadata(&attributes_path) else {
            continue;
        };
        let size = metadata.len();
        if size > ATTRIBUTES_FILE_BYTES {
            continue;
        }
        let Ok(bytes) = fs::read(&attributes_path) else {
            continue;
        };
        let content = String::from_utf8_lossy(&bytes);
        let local = relative
            .strip_prefix(directory.strip_prefix(root).ok()?)
            .ok()?
            .to_string_lossy()
            .replace('\\', "/");
        for line in content.lines().map(str::trim) {
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let mut fields = line.split_whitespace();
            let Some(pattern) = fields.next() else {
                continue;
            };
            if !attribute_pattern_matches(pattern, &local) {
                continue;
            }
            for attribute in fields {
                match attribute {
                    "linguist-generated" | "linguist-generated=true" => decision = Some(true),
                    "-linguist-generated" | "linguist-generated=false" => {
                        decision = Some(false);
                    }
                    _ => {}
                }
            }
        }
    }
    decision
}

fn attribute_pattern_matches(pattern: &str, relative: &str) -> bool {
    let pattern = pattern.trim_start_matches('/');
    if pattern.is_empty() || pattern.starts_with('!') {
        return false;
    }
    if !pattern.contains('/') {
        return relative.rsplit('/').next().is_some_and(|filename| {
            Pattern::new(pattern).is_ok_and(|value| value.matches(filename))
        });
    }
    Pattern::new(pattern).is_ok_and(|value| value.matches(relative))
}

#[cfg(test)]
mod tests {
    use std::error::Error;

    use super::*;

    #[test]
    fn generated_attribute_marks_tracked_bundle_without_content_guessing()
    -> Result<(), Box<dyn Error>> {
        let directory = tempfile::tempdir()?;
        let root = directory.path();
        let bundle = root.join("assets/viewer/graph.js");
        fs::create_dir_all(bundle.parent().ok_or("missing bundle parent")?)?;
        fs::write(&bundle, "(()=>{let x=1;})();\n")?;
        fs::write(
            root.join(".gitattributes"),
            "assets/viewer/graph.js linguist-generated=true\n",
        )?;
        assert!(source_is_generated(root, &bundle));
        Ok(())
    }

    #[test]
    fn explicit_false_attribute_overrides_parent_generated_rule() -> Result<(), Box<dyn Error>> {
        let directory = tempfile::tempdir()?;
        let root = directory.path();
        let source = root.join("assets/handwritten.js");
        fs::create_dir_all(source.parent().ok_or("missing source parent")?)?;
        fs::write(&source, "export const value = 1;\n")?;
        fs::write(
            root.join(".gitattributes"),
            "assets/*.js linguist-generated\n",
        )?;
        fs::write(
            root.join("assets/.gitattributes"),
            "handwritten.js -linguist-generated\n",
        )?;
        assert!(!source_is_generated(root, &source));
        Ok(())
    }

    #[test]
    fn ordinary_long_or_compact_source_is_not_guessed_generated() -> Result<(), Box<dyn Error>> {
        let directory = tempfile::tempdir()?;
        let source = directory.path().join("src/compact.js");
        fs::create_dir_all(source.parent().ok_or("missing source parent")?)?;
        fs::write(&source, "x".repeat(20_000))?;
        assert!(!source_is_generated(directory.path(), &source));
        Ok(())
    }

    #[test]
    fn source_package_named_build_is_not_an_output_directory() -> Result<(), Box<dyn Error>> {
        let directory = tempfile::tempdir()?;
        let source = directory.path().join("src/main/java/build/crab/Plan.java");
        fs::create_dir_all(source.parent().ok_or("missing source parent")?)?;
        fs::write(&source, "package build.crab;\n")?;
        assert!(!source_is_generated(directory.path(), &source));
        Ok(())
    }
}
