use std::fmt;
use std::str::FromStr;

use prolly::{Cid, Config, RuntimeConfig, Tree, TreeFormat};
use serde::{Deserialize, Deserializer, Serialize, Serializer};
use sha2::{Digest, Sha256};

use crate::{
    BuildProfile, ExtractionFingerprint, GraphArtifacts, HistoryError, canonical_json_bytes,
};

/// Version of the Compass history realization schema.
pub const HISTORY_SCHEMA_VERSION: u32 = 2;

/// Persistence treatment for one realization artifact.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ArtifactClass {
    /// Content that cannot be derived from other realization state.
    Authoritative,
    /// Presentation content regenerated by a versioned renderer.
    Derived,
    /// Attempt-local content excluded from realization identity.
    Operational,
}

/// Versioned registry description for a supported artifact.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct ArtifactRegistryEntry {
    /// Registry schema version.
    pub registry_version: u32,
    /// Safe path relative to a compatibility export directory.
    pub relative_path: String,
    /// Persistence treatment.
    pub class: ArtifactClass,
    /// IANA media type.
    pub media_type: String,
    /// Optional artifact schema version.
    pub schema_version: Option<u32>,
    /// Digest of authoritative content.
    pub content_digest: Option<[u8; 32]>,
    /// Verbatim authoritative storage when the content is not decomposed.
    pub storage: Option<Vec<u8>>,
    /// Exact derived renderer version.
    pub regeneration_version: Option<String>,
}

/// Verbatim bytes for a non-derivable authoritative sidecar.
pub type ArtifactContent = Vec<u8>;

/// Content-only tree handle persisted in a realization manifest.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct StoredTree {
    /// Root CID, or `None` for an empty tree.
    pub root: Option<[u8; 32]>,
    /// Persisted chunking and encoding format.
    pub format: TreeFormat,
}

/// Logical content-addressed storage shared by two complete realizations.
///
/// Counts come from Prolly reachability, not SQLite's private schema or file size.
#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
pub struct StructuralSharing {
    pub first_total_nodes: usize,
    pub second_total_nodes: usize,
    pub union_nodes: usize,
    pub shared_nodes: usize,
    pub first_total_bytes: usize,
    pub second_total_bytes: usize,
    pub union_bytes: usize,
    pub shared_bytes: usize,
}

impl StoredTree {
    /// Capture only the persisted portion of a Prolly tree handle.
    #[must_use]
    pub fn from_tree(tree: &Tree) -> Self {
        Self {
            root: tree.root.as_ref().map(|cid| cid.0),
            format: tree.config.format.clone(),
        }
    }

    /// Reopen a persisted tree with default runtime-only cache settings.
    #[must_use]
    pub fn to_tree(&self) -> Tree {
        Tree {
            root: self.root.map(Cid),
            config: Config {
                format: self.format.clone(),
                runtime: RuntimeConfig::default(),
            },
        }
    }
}

/// Immutable manifest for one complete graph realization.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct GraphVersion {
    pub schema_version: u32,
    pub git_commit: String,
    pub git_parents: Vec<String>,
    #[serde(default)]
    pub build_profile: BuildProfile,
    #[serde(default)]
    pub profile_digest: String,
    pub extraction_fingerprint: String,
    pub nodes_root: StoredTree,
    pub edges_root: StoredTree,
    pub hyperedges_root: StoredTree,
    pub analysis_root: StoredTree,
    pub metadata_root: StoredTree,
    pub node_count: u64,
    pub edge_count: u64,
    pub hyperedge_count: u64,
    pub analysis_count: u64,
    pub metadata_count: u64,
}

/// SHA-256 identity of canonical [`GraphVersion`] bytes.
#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub struct RealizationId([u8; 32]);

impl RealizationId {
    /// Derive a realization ID without operational fields.
    pub fn for_version(version: &GraphVersion) -> Result<Self, HistoryError> {
        let value = serde_json::to_value(version)?;
        Ok(Self(Sha256::digest(canonical_json_bytes(&value)?).into()))
    }

    /// Return strict lowercase hexadecimal text.
    #[must_use]
    pub fn as_hex(&self) -> String {
        let mut output = String::with_capacity(64);
        use fmt::Write;
        for byte in &self.0 {
            let _ = write!(output, "{byte:02x}");
        }
        output
    }
}

impl fmt::Display for RealizationId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.as_hex())
    }
}

impl FromStr for RealizationId {
    type Err = HistoryError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        if value.len() != 64
            || !value
                .bytes()
                .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
        {
            return Err(HistoryError::InvalidArtifacts(format!(
                "invalid realization ID {value}"
            )));
        }
        let mut bytes = [0u8; 32];
        for (index, pair) in value.as_bytes().chunks_exact(2).enumerate() {
            bytes[index] = (hex_nibble(pair[0]) << 4) | hex_nibble(pair[1]);
        }
        Ok(Self(bytes))
    }
}

impl Serialize for RealizationId {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(&self.as_hex())
    }
}

impl<'de> Deserialize<'de> for RealizationId {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        String::deserialize(deserializer)?
            .parse()
            .map_err(serde::de::Error::custom)
    }
}

/// Content-addressed proof that semantic extraction completed successfully.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct CompletionEvidence {
    pub extraction_succeeded: bool,
    pub allow_partial: bool,
    pub semantic_files_expected: u64,
    pub semantic_files_completed: u64,
    pub failed_chunks: u64,
}

/// Fully resolved SHA-1 or SHA-256 Git object identity.
#[derive(Clone, Debug, Eq, Hash, PartialEq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct CommitId(String);

impl CommitId {
    /// Borrow the normalized lowercase object ID.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl fmt::Display for CommitId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl FromStr for CommitId {
    type Err = HistoryError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        if matches!(value.len(), 40 | 64) && value.bytes().all(|byte| byte.is_ascii_hexdigit()) {
            Ok(Self(value.to_ascii_lowercase()))
        } else {
            Err(HistoryError::InvalidCommit(value.to_owned()))
        }
    }
}

impl CompletionEvidence {
    pub(crate) fn validate(&self) -> Result<(), HistoryError> {
        if self.extraction_succeeded
            && !self.allow_partial
            && self.semantic_files_expected == self.semantic_files_completed
            && self.failed_chunks == 0
        {
            Ok(())
        } else {
            Err(HistoryError::InvalidArtifacts(
                "semantic extraction is incomplete".to_owned(),
            ))
        }
    }
}

/// Complete immutable input to one history publication.
#[derive(Clone, Debug, PartialEq)]
pub struct PublishRequest {
    pub commit: CommitId,
    pub parents: Vec<CommitId>,
    pub profile: BuildProfile,
    pub fingerprint: ExtractionFingerprint,
    pub artifacts: GraphArtifacts,
    pub completion: CompletionEvidence,
    pub make_preferred: bool,
}

/// Addressable realization returned by publication and lookup.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct PublishedVersion {
    pub id: RealizationId,
    pub version: GraphVersion,
    pub preferred: bool,
}

const fn hex_nibble(value: u8) -> u8 {
    match value {
        b'0'..=b'9' => value - b'0',
        b'a'..=b'f' => value - b'a' + 10,
        _ => 0,
    }
}
